### ISSUE TITLE
Odroid C2 support

### ISSUE THREAD

**Issue by olluz** [lirios/lirios#55] opened 2018-03-28 11:13 UTC
Hi,
thanks a lot for adding Odroid support, but I've ran into several issues:

    lirios-init-build-env: for list_devices to work the directory seems to be wrong, it should be
    $DIR/conf/distro/machines/*.conf
    fetching meta-odroid fails, adding a revision in scripts/manifest.xml will help:
    revision="1979e36c9ff74fe668e2c89db2a919f7257ab4b9"
    adding a meta-liri/conf/distro/machines/odroid-c2.conf would be better
    a odroid-c2.conf is missing in meta-odroid/conf/machine/
    Can you please add one ?

Are you sure that Odroid C2 is supported ?

Thanks,
Oliver

**Comment by plfiorini** [comment] 2018-03-28 13:11
Duplicate of https://github.com/lirios/meta-liri/issues/5.

**Closed by plfiorini** 2018-03-28 13:11 UTC
