### ISSUE TITLE
password in usb live

### ISSUE THREAD

**Issue by foozzi** [lirios/lirios#33] opened 2017-03-19 17:06 UTC
What is default password for Live User in usb?? I now use virtual machines

**Comment by Collinthegeek** [comment] 2017-03-22 07:25
See #30 
Please check to see if your question has already been asked before submitting a new issue.

**Comment by plfiorini** [comment] 2017-04-12 14:33
Live media doesn't have passwords (neither `root` nor `liveuser`).
There are two possible issues here: you are either using Virtualbox that doesn't support Wayland properly or, most likely, hit a regression caused by libglvnd which is fixed in today ISO.

**Closed by plfiorini** 2017-04-12 14:33 UTC
