### ISSUE TITLE
No password posted anywhere for the live CD

### ISSUE THREAD

**Issue by jrcii** [lirios/lirios#30] opened 2017-03-06 06:20 UTC
Users who want to check out this distro are provided with a live CD which upon booting prompts for a password that is not documented anywhere.

<img width="794" alt="screen shot 2017-03-06 at 1 18 32 am" src="https://cloud.githubusercontent.com/assets/6308848/23598837/1246f4ee-020b-11e7-95b6-c04812ca1983.png">

**Comment by panospolychronis** [comment] 2017-03-06 16:38
I think there's no password for the moment, you may try whatever you want...

**Comment by crutchcorn** [comment] 2017-03-06 16:47
There is no password. Try hitting enter

**Comment by plfiorini** [comment] 2017-03-06 16:50
It should also be mentioned that nowadays SDDM on the Liri OS images does autologin.
If you are stuck at the prompt it means the desktop failed and often it happens on Virtual Box which is expected since it doesn't support Wayland. If that is the case you should be using VMWare with hw accel or qemu/virt-manager with QXL.

**Comment by jrcii** [comment] 2017-03-06 17:21
I tried no password multiple times, "password" "live" etc, and I get a loop back to the screen I posted, so I assume the issue is related to plfiorini's comment. I ran into this problem using VMWare Fusion 7 on OS X El Capitan + GeForce GT 750M (Late 2013 rMBP). 

I'm sure you guys have bigger fish to fry but if this is common maybe a good "someday" solution to this would be an error message for VM environments with Wayland support issues. If it's not common all the better, right? :)

**Comment by aft3rlife** [comment] 2017-03-18 06:29
I just wanted to add that I'm seeing this issue as well from a Live USB. Tried with the March 16th nightly.

**Comment by yangxuan8282** [comment] 2017-03-18 15:12
same issues for Mar 16th nightly, boot from usb

**Comment by Xmetalfanx** [comment] 2017-03-19 00:17
March 16 ISO and same issue here, after using the dd command and trying to look at it on actual hardware (not a VM)

**Comment by scootergrisen** [comment] 2017-03-24 14:10
So how can users try it if we can't get past that screen?

**Comment by Collinthegeek** [comment] 2017-03-24 14:19
Everyone read the previous comments in this thread. plfiorini said two weeks ago that if you get stuck at the login prompt it means the desktop failed to load. You should be able to troubleshoot that yourself, go to tty2 and run the shell manually to see what the error is.

**Comment by plfiorini** [comment] 2017-04-12 14:34
Turns out that libglvnd has a regression that broke the shell among other projects: a workaround has been applied and the issue is fixed with today ISO.

**Comment by Jack-Works** [comment] 2017-06-19 09:43
Same problem.

**Comment by plfiorini** [comment] 2017-06-19 09:50
VirtualBox doesn't support Wayland.

**Comment by Jack-Works** [comment] 2017-06-19 09:51
Hyper-V or VMware?

**Comment by plfiorini** [comment] 2017-06-19 10:26
VMware for sure, can't say Hyper-V for sure because I have never used it.

**Comment by vsnthdev** [comment] 2019-03-18 15:14
Today, I tried LiriOS and it is still stuck on the password prompt

**Comment by plfiorini** [comment] 2019-03-18 15:16
@vasanthdeveloper Did you try it on a virtual machine? If yes, which one (VMware, QEMU, VirtualBox, etc...)?

**Comment by vsnthdev** [comment] 2019-03-18 15:20
I don't think it is fair to  run an OS in development on Virtual Machine. So, ran it on my workstation :)

**Comment by plfiorini** [comment] 2019-03-18 16:54
@vasanthdeveloper Please boot the live, then press Ctrl+Alt+F2 to go to a VT. Authenticate as `liveuser` (no password required). Then type:

```sh
liri-session &> log.txt
```

And upload log.txt to https://paste.fedoraproject.org/ (or whatever pastebin equivalent) and put a link to it here.

**Comment by vsnthdev** [comment] 2019-03-18 19:18
Hello, after bit of experimentation I would like to point out a few things:
1. I would like to contibute to this project in any possible form.
2. The provided ISO is not UEFI Compatable (Downloaded from here).
3. ```wget``` which a program that is used quite frequently and is a bit important is not installed.
4. I don't know what package manager LiriOS uses, as ```pacman``` was not found and I read somewhere that LiriOS is based on Arch Linux.
5. When running the above command, the program ```liri-session``` says:
```
Aborted (core dumped)
```
6. There is no way to copy/save the log file from the Live USB, other than manually mounting an external HDD and copying into it.

Here is the log file you have requested, @plfiorini 
https://paste.fedoraproject.org/paste/HxME2e4W-Ax1gzoQY0tLOA

**Comment by plfiorini** [comment] 2019-03-27 11:00
@vasanthdeveloper Do you have a dual screen setup?

**Comment by vsnthdev** [comment] 2019-03-27 11:01
Yes, both are 1080p and run on Intel HD 630 Graphics

**Comment by plfiorini** [comment] 2019-03-27 11:02
Oh then it looks like a regression with dual screens, with one screen it works fine.
Will take a look.

**Comment by vsnthdev** [comment] 2019-03-27 11:03
Oh, then I will test LiriOS with only one screen and report back to you :)

**Comment by vsnthdev** [comment] 2019-03-29 15:04
Hey, so I checked LiriOS using only 1 monitor and it works like a charm. Although there are some rough edges to the operating system.

**Comment by plfiorini** [comment] 2019-04-12 15:54
The multiple monitor bug has been fixed, will be available in the next image.

**Comment by plfiorini** [comment] 2019-04-12 21:24
@vasanthdeveloper 

1. Depends on what you can do. You can test things out and report issues, write documentation, code, etc...
Documentation for developers is [here](https://liri-dev.readthedocs.io/en/latest/)
2. Add an issue, se #65
3. There is curl.
4. ISOs now are based on Fedora, the installed system uses `rpm-ostree` like Silverblue.
5. I'm investigating.
6. Now I have added `fpaste` to the live image.

**Comment by plfiorini** [comment] 2019-04-12 21:44
5. Seems to be fixed, but since the build server is already building an image, the fix will not be in the upcoming image.

**Comment by plfiorini** [comment] 2019-04-12 21:47
@vasanthdeveloper BTW we have a chat here: https://riot.im/app/#/room/#liri:matrix.org

**Comment by vsnthdev** [comment] 2019-04-13 04:58
The chat room says it no longer accepts new signups.

**Comment by plfiorini** [comment] 2019-04-15 08:29
Weird, works for me. Maybe something was wrong due to the recent attack. Try again.

**Closed** 2020-02-03 12:21 UTC
Labels: bug, livecd, upstream, x86_64

**Comment by Jack-Works** [comment] 2020-06-12 11:04
Happened in Hyper-V
