### ISSUE TITLE
NVIDIA proprietary driver support.

### ISSUE THREAD

**Issue by panospolychronis** [lirios/lirios#28] opened 2017-02-21 19:01 UTC
I know this might be hard enough, but gnome now runs with nvidia proprietary driver under wayland.. (EGLStreams..etc..).  So any chance to have the same for Liri as well?

**Comment by plfiorini** [comment] 2017-02-21 19:42
@panospolychronis Qt's eglfs QPA plugin supports it ever since Qt 5.7. QtWayland as well.
We have a fork here with more features that are a must have for a desktop system. I started posting a bunch of them upstream but it will take time.

Meanwhile we just need to sync our fork with upstream.

**Comment by panospolychronis** [comment] 2017-02-21 21:23
@plfiorini Thanks for your reply. It will be great to see this soon because it's necessary step which will make more people to try/test ...and why not contribute patches for Liri. It's about time to abandon Xorg and switch to wayland through this nice "highway" Liri.

**Comment by plfiorini** [comment] 2017-02-21 23:06
Link to detailed issue: https://github.com/lirios/wayland/issues/5

**Comment by edge226** [comment] 2017-08-07 19:39
I'm also interested in there being more options for Nvidia support.

**Comment by plfiorini** [comment] 2017-11-25 09:39
Implemented!

To test it type the following command on a tty:

```sh
QT_QPA_EGLFS_INTEGRATION=eglfs_kms_egldevice liri-session &> log
```

At the moment NVIDIA cannot be automatically detected so unfortunately you have to manually specify which integration you want to use.

**Comment by plfiorini** [comment] 2017-11-25 09:39
This issue is a duplicate of https://github.com/lirios/wayland/issues/5

**Closed by plfiorini** 2017-11-25 09:39 UTC
Labels: feature
