### ISSUE TITLE
Consider using Fedora as a base instead of Arch

### ISSUE THREAD

**Issue by Conan-Kudo** [lirios/lirios#23] opened 2017-01-15 12:17 UTC
In the [Welcome to Liri blog post](https://liri.io/blog/2017/01/01/welcome-to-liri.html), you mention the following quote:

> The OS is currently based on Arch Linux and at this time it doesn’t support OSTree yet so more work in this area will be done during 2017.

Perhaps consider using [Fedora](https://getfedora.org/) as a base instead of Arch. The Fedora Qt/KDE stack is kept up to date and close to upstream all the time (even receiving Qt, KF5, and Plasma upgrades in the middle of a release), which is good for you guys, as you probably want the latest and greatest that the Qt/KDE stack has to offer. The [Fedora KDE SIG](https://fedoraproject.org/wiki/SIGs/KDE) is a big and welcoming community that can help you accomplish your goals.

Fedora also has tooling for creating OSTree based install images (using [rpm-ostree](https://github.com/projectatomic/rpm-ostree), and while Fedora officially is using this for [Atomic Host cloud images](https://getfedora.org/en/atomic/), there has also been work on making an [Atomic Workstation](https://pagure.io/atomic-ws).

This would be very relevant to you as you want to have an OSTree based operating system. Fedora has the tooling in place to accomplish your goals, and you get other advantages, like UEFI boot on Secure Boot systems support, Raspberry Pi 2 and newer support, etc.

**Comment by plfiorini** [comment] 2017-01-15 18:08
I know the virtues of Fedora, I was using it before but went back to Arch Linux for the Liri images.
While it is certainly a much more stable and tested base it is a bit painful for Qt. For instance when I first prepared the Liri images F25 was not even released and my only choice was F24 which to this day has Qt 5.6.x. Had to wait until F25 alpha came out only to find out that making a live image was impossibile due to package conflicts. I can only assume that for Qt 5.8 I have to wait F26 now.
Not to mention the instability of the rpm-ostree tools and the pain of kickstarts being a second class citizen now without providing a better alternative (no building live images with Anaconda is not as easy as kickstarts nor as archiso).

**Comment by Conan-Kudo** [comment] 2017-01-15 18:23
@plfiorini What package conflicts were there? I'm sure that @rdieter would be interested to know and help resolve those issues. 

As for kickstarts, `lorax` and `livecd-tools` both offer first class support for it. I'm the primary contributor/maintainer of `livecd-tools`, while the @bcl is the primary developer/maintainer to livemedia-creator, which is part of `lorax`.

If there are issues that need to be resolved, please feel free to talk to me or anyone in Fedora KDE SIG about them, and we'd be happy to help.

**Comment by Conan-Kudo** [comment] 2017-01-15 18:24
As for kickstarts for OSTree creation, @cgwalters is the best man to talk to about that.

**Comment by kkofler** [comment] 2017-01-15 19:00
I build Fedora Remix ISOs with a one-line livecd-creator (from livecd-tools) invocation.
https://svn.calcforge.org/viewvc/kannolo/trunk/kickstart/

**Comment by plfiorini** [comment] 2017-01-15 19:36
@Conan-Kudo can't remember the packages that were conflicting but it's likely it was fixed after the alpha. The point is that I don't want to use Fedora alpha just to have the latest Qt release, it's painful.

@kkofler I used too for a long time, https://github.com/lirios/kickstart  I'm glad that now it uses dnf but the main problem is that it's unlikely Qt will be updated as soon as it is released and I often need the latest version since it contains many bug fixes. Since Fedora cares about stability I understand the implications of a major toolkit update and the reason why it needs its time.

**Comment by plfiorini** [comment] 2017-01-15 19:41
Found it @Conan-Kudo:

```
libcrypt conflicts with libcrypt-nss-2.24-3.fc25.x86_64                                                                                                                                                                                                       
libcrypt-nss conflicts with libcrypt-2.24-3.fc25.x86_64﻿
```

**Comment by Conan-Kudo** [comment] 2017-01-15 22:00
@plfiorini 

Ah, that's because both are equal providers. It's an easy fix, just add the following lines:

```
libcrypt-nss
-libcrypt
```

**Comment by kkofler** [comment] 2017-01-15 22:29
Including a newer Qt than what Fedora includes is what Copr is for.

That said, I am not happy with the decision to not upgrade F24 beyond 5.6 and will continue pushing for Qt upgrades in our releases. The problem is that the one who does the work decides, and I do not have the time to work on the whole Qt stack anymore. (I am already spending enough time on that QtWebEngine PITA.)

**Comment by kekpons** [comment] 2017-01-16 00:19
Please don't use fedora. Thanks.

**Comment by plfiorini** [comment] 2017-02-06 10:21
@kkofler Exactly the reason why Copr is not stable. For example smooth upgrade to Qt 5.8 on Fedora 25 is quiet impossible:

```
Error: nothing provides qt5-declarative-doc needed by qt5-qt3d-doc-5.8.0-1.fc25.noarch.
```

This happens quiet often with Qt Copr, it is simply not meant to be used in production rather for testing.

Closing the issue now because I don't think using Fedora as base will happen soon, if ever.

**Closed** 2017-02-06 10:21 UTC
